version: '3.7'

services:
    backend:
        container_name: "backend"
        build:
          context: "C:\\Users\\malol\\OneDrive - Fondation EPF\\EPF\\4A\\S2\\DevOps\\MMMDE4IN21_DevOps\\Lab1\\API\\simple-api-student-main"
        networks:
          - app-network
        depends_on:
          - database

    database:
        container_name: "database"
        build:
          context: "C:\\Users\\malol\\OneDrive - Fondation EPF\\EPF\\4A\\S2\\DevOps\\MMMDE4IN21_DevOps\\Lab1\\DataBase"
        networks:
          - app-network

    httpd:
        build:
          context: "C:\\Users\\malol\\OneDrive - Fondation EPF\\EPF\\4A\\S2\\DevOps\\MMMDE4IN21_DevOps\\Lab1\\Http server"
        ports:
          - "8080:80"
        networks:
          - app-network
        depends_on:
          - backend

networks:
    app-network:
