name: CI devops 2024

on: 
  push: 
    branches:
      - main
  pull_request: 

jobs:
  build-and-push-docker-image:
    needs: test-backend
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image and push backend
        uses: docker/build-push-action@v3
        with:
          context: ./API/simple-api-student-main
          tags:  ${{secrets.DOCKERHUB_USERNAME}}/link_app-backend:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build image and push database
        uses: docker/build-push-action@v3
        with:
          context: ./DataBase
          tags:  ${{secrets.DOCKERHUB_USERNAME}}/link_app-database:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build image and push httpd
        uses: docker/build-push-action@v3
        with:
          context: ./Http server
          tags:  ${{secrets.DOCKERHUB_USERNAME}}/link_app-httpd:latest
          push: ${{ github.ref == 'refs/heads/main' }}
