name: CI devops 2024 #name of the workflow

on: #Specifies the events that trigger the workflow. In this case, the workflow runs on pushes to the main and develop branches, as well as on pull requests.
  push: #action that start the workflow
    branches: #branches when pushed on that start the workflow
      - main
      - develop
  pull_request: 

jobs: #section of actions to run
  test-backend: #name of the job
    runs-on: ubuntu-22.04 #definition of the os used
    steps: #definition of section step
      - uses: actions/checkout@v2.5.0 #set of the action to use

      - name: Set up JDK 17 #name of the action
        uses: actions/setup-java@v3
        with: #section definition of the caratristics of the aciton
          java-version: '17'
          distribution: 'adopt'

      # build your app with Maven and include SonarCloud analysis
      - name: Build, test with Maven, and run SonarCloud analysis
        run: mvn -B verify sonar:sonar -Dsonar.projectKey=devopsmalolepf_malolepf -Dsonar.organization=devopsmalolepf -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}
        working-directory: ./API/simple-api-student-main/
  
  # define job to build and publish docker image
  build-and-push-docker-image:
    needs: test-backend
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-22.04

    # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image and push backend
        uses: docker/build-push-action@v3
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ./API/simple-api-student-main
          # Note: tags has to be all lower-case
          tags:  ${{secrets.DOCKERHUB_USERNAME}}/link_app-backend:latest
          # build on feature branches, push only on main branch
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build image and push database
        uses: docker/build-push-action@v3
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ./DataBase
          # Note: tags has to be all lower-case
          tags:  ${{secrets.DOCKERHUB_USERNAME}}/link_app-database:latest
          # build on feature branches, push only on main branch
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build image and push httpd
        uses: docker/build-push-action@v3
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ./Http server
          # Note: tags has to be all lower-case
          tags:  ${{secrets.DOCKERHUB_USERNAME}}/link_app-httpd:latest
          # build on feature branches, push only on main branch
          push: ${{ github.ref == 'refs/heads/main' }}
